### ISSUE TITLE
Ligatures don't work

### ISSUE THREAD

**Issue by subnut** [arrowtype/recursive-code-config#20]
## Build environment
- Linux
- python3.10

## config.yml
```yml
Family Name: Custom

Fonts:

  Regular:
    MONO: 1
    CASL: 1
    wght: 350
    slnt: 0
    CRSV: 0

  Italic:
    MONO: 1
    CASL: 1
    wght: 350
    slnt: -5
    CRSV: 0

  Bold:
    MONO: 1
    CASL: 1
    wght: 600
    slnt: 0
    CRSV: 0

  Bold Italic:
    MONO: 1
    CASL: 1
    wght: 600
    slnt: -5
    CRSV: 0

Code Ligatures: True

Features:
  - ss01
  - ss02
  - ss07
  - case
```
