### ISSUE TITLE
Support for proportional fonts

### ISSUE THREAD

**Issue by matj1** [arrowtype/recursive-code-config#24]
I would like to have a custom proportional variant of Recursive for programming. I used this configurator, set MONO to 0.25, and the result looks wrong.

Please, make it work with proportional fonts too.

The text editor works well with Recursive Sans Linear Static, so the problem is probably that this configurator forces every glyph into the same width. I want that every character would keep its original width.

My variant looks like this:

![text in Recursive Mono Proportional having wrongly placed glyphs](https://github.com/arrowtype/recursive-code-config/assets/22873928/6bc8ff96-357e-4677-bed0-335d35fbc4df)

This is my configuration:

```
Family Name: Proportional

Fonts:

  Regular:
    MONO: 0.25
    CASL: 0
    wght: 425
    slnt: 0
    CRSV: 0

  Italic:
    MONO: 0.25
    CASL: 1
    wght: 425
    slnt: -5
    CRSV: 1

  Bold:
    MONO: 0.25
    CASL: 0
    wght: 750
    slnt: 0
    CRSV: 0

  Bold Italic:
    MONO: 0.25
    CASL: 1
    wght: 750
    slnt: -5
    CRSV: 1

Code Ligatures: True

Features:
- ss09
- ss10
- ss11
```
