### ISSUE TITLE
Feature ss04 not working

### ISSUE THREAD

**Issue by milandoshljak** [arrowtype/recursive-code-config#4]
After build every feature seems to work except ss04 i.e. "simplified i".

![2020-08-18_14-43](https://user-images.githubusercontent.com/57806387/90515316-c36d8280-e162-11ea-8273-4530b2a005da.png)

**Comment by 0xShamil** [comment]
As of `1.066`, `ss04` still does not work as expected

**Comment by arrowtype** [comment]
Hi @0xShamil, can you please let me know which fonts you are using (TTF/OTF/variable), and on which platform & app?

For me, these seem to be working on a random sampling:

![image](https://user-images.githubusercontent.com/45946693/98989896-bd840500-24f7-11eb-92cc-22eee1b4b8f6.png)

**Comment by arrowtype** [comment]
One thing that might solve your problem in the near term, potentially, would be configuring a custom build at 

https://github.com/arrowtype/recursive-code-config

**Comment by zou000** [comment]
Seems related: In my case, the feature **ss08** is not working.  I built the custom font with the following config
```yaml
# Family Name

# The name you want after "Rec Mono" in your custom fonts.
# Example: "Custom" will yield the family "Rec Mono Custom".
# Keep under 13 characters in length to avoid potential OS bugs.

Family Name: Custom

# -----------------------------------------------------------------------------
# Font Styles

# The variable axis values for the Regular, Italic, Bold, & Bold Italic fonts.
# See https://recursive.design for more information on these.

# MONO: 0 for Sans, 1 for Mono (or anything in-between)
# CASL: 0 for Linear, 1 for Casual (or anything in-between)
# wght: 300–1000 (realistically, about 400 for Regular & Italic and about 700 for Bold & Bold Italic)
# slnt: 0 to -15 (negative numbers are more slanted, and approximately equal to degrees of slope)
# CRSV: 0 (0 for Roman, 1 for Cursive)

Fonts:

  Regular:
    MONO: 1
    CASL: 1
    wght: 325
    slnt: 0
    CRSV: 0

  Italic:
    MONO: 1
    CASL: 1
    wght: 375
    slnt: -10
    CRSV: 1

  Bold:
    MONO: 1
    CASL: 1
    wght: 700
    slnt: 0
    CRSV: 0

  Bold Italic:
    MONO: 1
    CASL: 1
    wght: 700
    slnt: -10
    CRSV: 1

# -----------------------------------------------------------------------------
# Font Features

# Freeze in code ligatures? True or False
Code Ligatures: True

# Include font features to freeze in stylistic options. Copy them below to use.
# See README for details.

# These options only have an affect at CRSV<=0.5 (Roman/normal styles)
# ss01 # single-story a
# ss02 # single-story g
# ss03 # simplified f
# ss04 # simplified i
# ss05 # simplified l
# ss06 # simplified r

# These options affect both Roman & Cursive styles
# ss07 # serifless L and Z
# ss08 # simplified @
# ss09 # simplified 6 and 9
# ss10 # dotted 0
# ss11 # simplified 1

# (Keep the hyphen before each list item)
Features:
- ss03 # simplified f
- ss05 # simplified l
- ss07 # serifless L and Z
- ss08 # simplified @
- ss09 # simplified 6 and 9

# That’s it! See README for next steps.
~                                                                     
```
